CREATE SCHEMA IF NOT EXISTS app;

CREATE TABLE IF NOT EXISTS app.income_from_sells (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_aquired date NOT NULL,
    date_sold date NOT NULL,
    symbol varchar(32) NOT NULL,
    security_name varchar(255) NOT NULL,
    isin varchar(20) NOT NULL,
    country varchar(50) NOT NULL,
    quantity numeric(20, 8) NOT NULL,
    cost_basis numeric(19, 4) NOT NULL,
    gross_proceeds numeric(19, 4) NOT NULL,
    gross_pnl numeric(19, 4) NOT NULL,
    currency varchar(10) NOT NULL
);


-- rollback
DROP TABLE IF EXISTS app.income_from_sells;
