CREATE TABLE income_from_sells (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_aquired date NOT NULL,
    date_sold date NOT NULL,
    symbol varchar(10) NOT NULL,
    security_name varchar(255) NOT NULL,
    isin varchar(20) NOT NULL,
    country varchar(50) NOT NULL,
    quantity numeric NOT NULL,
    cost_basis numeric NOT NULL,
    gross_proceeds numeric NOT NULL,
    gross_pnl numeric NOT NULL,
    currency varchar(10) NOT NULL
);


-- rollback
DROP TABLE income_from_sells;
