CREATE TABLE other_income_fees (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_aquired date NOT NULL,
    symbol varchar(10) NOT NULL,
    security_name varchar(255) NOT NULL,
    isin varchar(20) NOT NULL,
    country varchar(50) NOT NULL,
    gross_amount numeric NOT NULL,
    withholding_tax varchar(20) NOT NULL,
    net_amount varchar(20) NOT NULL,
    currency varchar(10) NOT NULL
);


-- rollback
DROP TABLE other_income_fees;
