spring.application.name=spring-server

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/server_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:MyStrongP@ssword1}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=never

server.port=8080
